# This workflow will run the coverage reports and publish it on github pages.
name: Coverage & Gas Report

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

on:
  push:
    branches: [master, develop]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  coverage:
    runs-on: ubuntu-latest
    name: Build Coverage & Gas Report
    steps:
      # setup env
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install lcov
        run: sudo apt-get -y install lcov
        shell: bash

      - uses: ./.github/actions/install

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Run coverage
        run: |
          echo MAINNET_RPC_URL=${{ secrets.MAINNET_RPC_URL }} >> .env
          yarn compile
          yarn coverage:html

      # Deploy to gh pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./coverage"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
